### ISSUE TITLE
Please make v3 available on the web

### ISSUE THREAD

**Issue by rpgoldman** [SynBioDex/SbolStandardWebsite#126]
I have found that, although it *mostly* supports loading locally, the very popular Ontology tool Protégé encounters issues when I work with v3, with the ontology IRI `<http://sbols.org/v3>`, because that URL does not respond with the ontology.

That URL returns something that looks *almost* like a 404 but that ... isn't? (P.S. I thought the oddball look of the following might be a browser issue, but it looks the same on both Safari and Firefox).

<img width="538" alt="image" src="https://user-images.githubusercontent.com/3274/127508103-90f36047-e81e-4401-b6ee-32832ea25e94.png">

**Comment by jamesscottbrown** [comment]
I think that this is now resolved: [http://sbols.org/v3](http://sbols.org/v3) now redirects to [https://raw.githubusercontent.com/SynBioDex/sbol-owl3/main/sbolowl3.rdf](https://raw.githubusercontent.com/SynBioDex/sbol-owl3/main/sbolowl3.rdf).
