### ISSUE TITLE
Missing pySBOLOverview.pdf file

### ISSUE THREAD

**Issue by jamesscottbrown** [SynBioDex/SbolStandardWebsite#139]
The [Python page](https://sbolstandard.org/libraries/python/) on the SBOL site has a broken link to a [pySBOLOverview.pdf](https://sbolstandard.org/docs/pySBOLOverview.pdf) file.

Does anyone have a copy of this file, or should the link be deleted?

@bbartley

**Comment by tcmitchell** [comment]
I spoke with @bbartley and the origins and whereabouts of `pySBOLOverview.pdf` are a mystery. This reference should be deleted. I'll do that in an upcoming pull request.
