### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jamesscottbrown** [SynBioDex/SbolStandardWebsite#154]
The README should be updated with instructions on how to contribute by editing the website.

**Comment by cjmyers** [comment]
Should start with a warning about how the process of proposing a change in the website would work: 1) Create a local working version of the website, 2) make changes, 3) make a pull request ,4) assign an editor to review your changes, 5) the change will be accepted or not. 

How to have a local working version of the website
Download and install hugo-extended
Download Go language
Clone repository
Run hugo server
Run hugo mod clean

Uptading
Publications
Tools
Personal information
Events

Resources to common problems/issues:
Wowchemy website
Discord channel

**Comment by jamesscottbrown** [comment]
See [PR #](https://github.com/SynBioDex/SbolStandardWebsite/pull/163)
