### ISSUE TITLE
Broken links for event images

### ISSUE THREAD

**Issue by jamesscottbrown** [SynBioDex/SbolStandardWebsite#174]
[Several events](https://github.com/SynBioDex/SbolStandardWebsite/search?q=wp-content) contain broken links to images, using URLs containing `/wp-content/`.

Does anyone have a copy of these?

They [don't seem](https://web.archive.org/web/*/http://sbolstandard.org/wp-content/uploads/2018/05/soundbio5.png) to be on the Wayback Machine.

**Comment by tcmitchell** [comment]
IWBDA 2019 will be fixed by #175

**Comment by tcmitchell** [comment]
The only missing wp-content is now on the SoundBioLab event page https://sbolstandard.org/event/2018/soundbiolab/

The event seems to have fallen off the [SoundBioLab past events page](https://www.sound.bio/pastevents). We discussed and decided that the image links can be removed from the page and only the text will remain.
