### ISSUE TITLE
FAQ - SBOL Community mailing lists

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SbolStandardWebsite#18]
There are actually 4 lists, should include sbol-visual.  Maybe instead of listing all the lists there, instead link to contact which has these details.

**Comment by hasanbaig** [comment]
Where do you want SBOL visual list to be included? I am checking this link out (https://synbiodex.github.io/SbolStandardWebsite/contact/) and I see that the link is already there.

**Comment by hasanbaig** [comment]
oh i see you meant in FAQs

**Comment by PrashantVaidyanathan** [comment]
Fixed with #22
