### ISSUE TITLE
Create a linkchecker Github Action that checks for broken links every week before SBOL editor meetings. 

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SbolStandardWebsite#185]

**Comment by tcmitchell** [comment]
We have a link checker action: https://github.com/SynBioDex/SbolStandardWebsite/blob/master/.github/workflows/check-links.yml

I think this issue can be closed once we decide on the frequency of the action. Should we change the action from monthly to weekly? Or leave it as is?

**Comment by tcmitchell** [comment]
I looked at the output and it lists a few URLs as errors, but they work for me in manual testing. For example:
* See https://github.com/SynBioDex/SbolStandardWebsite/actions/runs/4060345836/jobs/6989344866#step:3:20
* See https://github.com/SynBioDex/SbolStandardWebsite/actions/runs/4060345836/jobs/6989344866#step:3:29

**Comment by jamesscottbrown** [comment]
> Should we change the action from monthly to weekly? Or leave it as is?

I'd leave it as it is - the action takes a while to run, so making it run weekly will use more of our allocation of minutes for running GitHub Actions.

> it lists a few URLs as errors, but they work for me in manual testing

This is the case for the links to ACS SynBio papers, but there are still a small number of links that are broken.
