### ISSUE TITLE
Update SBOL Java libraries to point to libSBOLj3 page

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SbolStandardWebsite#190]
Create a description page for libSBOLj3 that links to the libSBOLj3 repo

Link to the libSBOLj2 page as an older library, see pySBOL3 page for example

**Comment by tcmitchell** [comment]
@goksel @cjmyers Where does this stand? I can update the website if you can provide content and appropriate links. 

I think we agreed in the past that moving libSBOLj3 from https://github.com/goksel/libSBOLj3 to SynBioDex is a prerequisite. Let me know if this has changed.

**Comment by cjmyers** [comment]
@goksel will need to respond on this one

**Comment by goksel** [comment]
This has now been done. the libSBOLj3 repository has been moved to SynBioDex. Detailed content and links about the website update are provided here: https://github.com/SynBioDex/SbolStandardWebsite/issues/230
