### ISSUE TITLE
Migrating SBOL specification and PDFs from Co.mbine.org before it goes down.

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SbolStandardWebsite#195]
These are all re-directs http://co.mbine.org/admin/build/path/list/sbol that are related to SBOL specification versions and pdfs. We have to migrate this to the SBOLSTANDARD website.

**Comment by tcmitchell** [comment]
I can setup pages like `https://sbolstandard.org/specifications/sbol/$version` (N.B. `/`, not `.` between `sbol` and `$version`) that can redirect within `https://sbolstandard.org` to other pages where we publish info about a given specification/version combination.
With this in place, if a browser visits http://identifiers.org/combine.specifications it will be redirected to http://co.mbine.org/standards, which will in turn redirect to https://sbolstandard.org/specifications, which will in turn redirect internally to pages under https://sbolstandard.org/datamodel-specification/ or https://sbolstandard.org/visual-specification/

**Comment by Fontanapink** [comment]
@tcmitchell can you show me how this can be done, and then we split up the identifiers?

**Comment by tcmitchell** [comment]
@Fontanapink see #135 and #140 for the approach I was planning to use. I can prototype a page if that would be helpful.

**Comment by tcmitchell** [comment]
@Fontanapink I have pushed branch `195-identifiers` with an example page. If you run it locally and visit `/specifications/sbol/version-2.2.0` you will be redirected to `/datamodel-specification/version-2.2.0/`. I can continue to work on the data model links if you want to pick up the visual links.

The content at `/datamodel-specification/version-2.2.0/` is copied from co.mbine.org, and is easily updated. This is only intended as a demonstration of the redirect, or alias, capability built into Hugo.

**Comment by cjmyers** [comment]
@Fontanapink any thoughts on the redirection from the COMBINE website as described in the comments above.  Now that Tom has finished the SBOL standard pages, we should check this out.

**Comment by tcmitchell** [comment]
I think this work is complete. Are there any remaining tasks?

@cjmyers @jamesscottbrown

**Comment by cjmyers** [comment]
I agree
