### ISSUE TITLE
FAQ Paper Citations

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SbolStandardWebsite#20]
Maybe simplify to:

What papers should I cite for SBOL data?

    SBOL 1 (NBT)
    SBOL 2 (ACS SynBio)
    SBOL 3 (Frontiers)
    SBOL Specifications (JIB)

What papers should I cite for SBOL visual?

     SBOL VIsual 1 (PLoS)
     SBOL Visual 2 (ACS SynBio)
     SBOL Visual Specification (JIB)

What papers should I cite for SBOL libraries and utilities?

     libSBOLj
     pySBOL
     sboljs
     SBOL validator/converter

**Comment by PrashantVaidyanathan** [comment]
Fixed in PR #22
