### ISSUE TITLE
Add 3.1.0 specification 

### ISSUE THREAD

**Issue by LukasBuecherl** [SynBioDex/SbolStandardWebsite#215]
Currently the website allows to download the specification up to 3.0.1. Now that 3.1.0 is out we should add it to the website.

The new release should also be added to `combine-org` via a PR there. See https://github.com/SynBioDex/SbolStandardWebsite/issues/209 for a recent example of doing that.

**Comment by tcmitchell** [comment]
@LukasBuecherl we need a summary of version 3.1.0 of the specification to post on the web site. See https://sbolstandard.org/datamodel-specification/ for examples. If you or someone else can write that executive summary, I can do the modifications to the web site to post 3.1.0.

@Gonza10V I will also need the final PDF whenever it is ready. There is no hurry.

**Comment by LukasBuecherl** [comment]
@tcmitchell Sounds good. I will write that over the weekend. I compiled the new PDF with the fixed typos that I can send to you id needed.

**Comment by jamesscottbrown** [comment]
It will also need to be added to https://github.com/combine-org/combine-specifications

**Comment by LukasBuecherl** [comment]
Here is the summary from the abstract:

SBOL Version 3.1.0 improves on version 3.0.0 by including a number of corrections and clarifications as well as several other updates and enhancements.  First, this version includes a complete set of validation rules for checking whether documents are valid SBOL 3.  Second, the best practices section has been moved to an online repository that allows for more rapid and interactive of sharing these conventions. Third, it includes updates based upon six community approved enhancement proposals. Two enhancement proposals are related to the representation of an object's namespace.  In particular, the Namespace class has been removed and replaced with a namespace property on each class.  Another enhancement is the generalization of the CombinatorialDeriviation class to allow direct use of Features and Measures. Next, the Participation class now allow Interactions to be participants to describe higher-order interactions.  Another change is the use of Sequence Ontology}terms for Feature orientation.  Finally, this version of SBOL has generalized from using Unique Reference Identifiers (URIs) to Internationalized Resource Identifiers (IRIs) to support international character sets.

**Comment by tcmitchell** [comment]
* SBOL Standard Website PR: https://github.com/SynBioDex/SbolStandardWebsite/pull/219
* COMBINE PR: https://github.com/combine-org/combine-specifications/pull/32

**Comment by tcmitchell** [comment]
SBOL 3.1.0 has been added to the SBOL Standard Website and to the COMBINE web site (thus making the identifiers.org link live). The citation needs to be added when it is available. Closing this one after having added #220 for the citation work.
