### ISSUE TITLE
Fixes to Community About Page

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SbolStandardWebsite#28]
Move the github link to Community Media to the Outreach page

Change the to join to a link to the form rather than editors email.

**Comment by hasanbaig** [comment]
@cjmyers: do you really want the github link to be connected to Outreach page (https://synbiodex.github.io/SbolStandardWebsite/community-outreach/) or was that a typo?

**Comment by hasanbaig** [comment]
The link to contact editors has been updated. Only waiting for @cjmyers reply about the above comment. Will update and close the issue then.

**Comment by cjmyers** [comment]
Yes, because these slides in Community Media were mostly presented at the Outreach events.

**Comment by hasanbaig** [comment]
> Yes, because these slides in Community Media were mostly presented at the Outreach events.

So should it be placed something like "The list of SBOL outreach events can be seen here (link to Outreach page)" ? 
It does not make sense to update only the link without updating the sentence.

**Comment by cjmyers** [comment]
Maybe something like this:

Below is a list of outreach events that SBOL has been involved in to educate the community about SBOL and its capability.
The presentation materials for many of these outreach events can be found in the SBOL Community Media repository found here, and they are made freely available via a Creative Commons license.

**Comment by hasanbaig** [comment]
> Maybe something like this:
> 
> Below is a list of outreach events that SBOL has been involved in to educate the community about SBOL and its capability.
> The presentation materials for many of these outreach events can be found in the SBOL Community Media repository found here, and they are made freely available via a Creative Commons license.

This paragraph can be updated directly on "Outreach" page as we are pointing to "Below is a list". Should I also update the same statement (with slight manipulation) on Community About Page?

**Comment by cjmyers** [comment]
This is for the Outreach page.  I wanted to delete the link to the repo on the About page.

**Comment by cjmyers** [comment]
And the sentence mentioning the repo.

**Comment by hasanbaig** [comment]
So, when a user access "Community About" page, they will see the following sentence at the top:

Here (link to outreach page) is a list of outreach events that SBOL has been involved in to educate the community about SBOL and its capability. The presentation materials for many of these outreach events can be found in the SBOL Community Media repository found here, and they are made freely available via a Creative Commons license.

**Comment by hasanbaig** [comment]
Done!

**Comment by cjmyers** [comment]
No, they should only see:

"The SBOL community works actively on the SBOL data model and visual standard, participates in online discussions, and meets semi-annually. We represent over 170+ members from 17 different countries, 42 institutions, and 28 different industries. Many of our members are also actively involved in other standards communities, like the Systems Biology Markup Language (SBML) and Systems Biology Graphical Notation (SBGN).

To join our growing community, contact the SBOL Editors here."

The Community -> Outreach page is the one I'm asking to change to:

"Below is a list of outreach events that SBOL has been involved in to educate the community about SBOL and its capability.
The presentation materials for many of these outreach events can be found in the SBOL Community Media repository found here, and they are made freely available via a Creative Commons license."

**Comment by hasanbaig** [comment]
oh now that makes it more clear. It was a bit confusing for me in the original issue statement. I will do it right away

**Comment by hasanbaig** [comment]
Done. Please check and close the issue.

**Comment by cjmyers** [comment]
"here" on the outreach page should be a link to the Community Media github

**Comment by hasanbaig** [comment]
done!
