### ISSUE TITLE
Add SBOL Visual examples from the spec

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SbolStandardWebsite#42]

**Comment by JMante1** [comment]
it would also be nice if the visual examples page had the in page examples before the paper examples

**Comment by jamesscottbrown** [comment]
The examples from the specification are now being pushed from the SBOL-visual repo by a script: https://sbolstandard.org/visual-spec-examples/

This is a separate page to the page of SBOL examples from papers: https://sbolstandard.org/visual-examples/
