### ISSUE TITLE
Add option to email sbol editors if form is not accessible

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SbolStandardWebsite#45]

**Comment by hasanbaig** [comment]
I think we can also check if there is any "template" available for "Contact" on Hugo. We can hook it up on our website, rather than using google forms or asking people to send out an email to editors

**Comment by Fontanapink** [comment]
Added option for email.

**Comment by Fontanapink** [comment]
> I think we can also check if there is any "template" available for "Contact" on Hugo. We can hook it up on our website, rather than using google forms or asking people to send out an email to editors

I looked into this, and it looks that we would need to pay a service to have that.

**Comment by hasanbaig** [comment]
We can have a "contact" widget.

**Comment by Fontanapink** [comment]
Fixed
