### ISSUE TITLE
Upper and lower cases indistinguishable in tool links

### ISSUE THREAD

**Issue by jamesscottbrown** [SynBioDex/SbolStandardWebsite#47]
The names of tools on the homepage are written in a typeface that makes upper and lower case indistinguishable, but many of the tools do contain a mixture of cases (e..g, `fSBOL`).

One easy fix would be to change these to use the `<b>` tag rather than `<h4>`.

**Comment by PrashantVaidyanathan** [comment]
Thanks. These have been addressed in #59 
I now refer to the libraries by the programming language it was written in rather than the name of the library itself.
