### ISSUE TITLE
Validator and Converter

### ISSUE THREAD

**Issue by JMante1** [SynBioDex/SbolStandardWebsite#50]
the fact that the validator and converter lead to the same page might be confusing

**Comment by cjmyers** [comment]
They are actually different pages.  Is that not what you are seeing?

**Comment by JMante1** [comment]
Sorry they are slightly different pages but the validator has conversion options on the page which is confusing

**Comment by cjmyers** [comment]
Yeah, that is by design. They are the same thing, but different UI.  We had some people complain that the validator had too many options for someone just wanting to convert a GenBank file.  I don't use the converter front-end myself, since the validator is more full-feature.

**Comment by PrashantVaidyanathan** [comment]
I'm closing this issue for now since it seems that the pages are showing up as intended. This can be re-opened in case there are additional actionable items.
