### ISSUE TITLE
Dates for meetings and outreach

### ISSUE THREAD

**Issue by JMante1** [SynBioDex/SbolStandardWebsite#52]
community outreach and meetings date formats are not applied consistently some are 2020/6-7/6 and others are 2020/6/6-2020/7/6 (also that date format is unhelpful for sorting and being able to have a sortable table so you can see most recent conference or for example all iwbda conferences would be nice)

**Comment by hasanbaig** [comment]
will fix that too.

**Comment by hasanbaig** [comment]
Fixed!
