### ISSUE TITLE
SBOL Logo for Dark Theme

### ISSUE THREAD

**Issue by hasanbaig** [SynBioDex/SbolStandardWebsite#72]
S, B and L in SBOL Logos in dark theme should turn to white. It is otherwise, not visible. I think we can choose to have two different logos for Light and Dark theme using CSS.

**Comment by Fontanapink** [comment]
We might have to use this:

https://hiddedevries.nl/en/blog/2018-12-24-making-single-color-svg-icons-work-in-dark-mode

**Comment by Fontanapink** [comment]
https://github.com/wowchemy/wowchemy-hugo-modules/discussions/1961

**Comment by Fontanapink** [comment]
Check this also:
https://github.com/wowchemy/wowchemy-hugo-modules/discussions/1961

**Comment by Fontanapink** [comment]
and this https://github.com/wowchemy/wowchemy-hugo-modules/blob/cdcfa2da28e23893b000c9da1498cb8283033907/wowchemy/layouts/partials/navbar.html#L8

**Comment by Fontanapink** [comment]
Just deleted the option for a dark-themed website
