### ISSUE TITLE
SBOL Data Model Ontology URL from the paper does not work anymore

### ISSUE THREAD

**Issue by goksel** [SynBioDex/SbolStandardWebsite#78]
The SBOL-OWL paper used the following URL to refer to the SBOL ontology: https://sbolstandard.org/ontology
This URL has recently been changed with "https://sbolstandard.org/datamodel-ontology/". Can we please either use the former or include a redirection to the latter. I am not sure if the "datamodel ontology" is the right term. I think SBOL ontology may be better for adoption by others.

**Comment by hasanbaig** [comment]
Fixed. Please check
