### ISSUE TITLE
Java and Javascript CRISPR circuit example links not pointing to the correct document

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SbolStandardWebsite#86]
https://github.com/SynBioDex/libSBOLj/tree/master/docs/tutorials/crisprExample
https://github.com/SynBioDex/libSBOLj/tree/master/docs/tutorials/gettingStarted
https://sbolstandard.org/libraries/java/
https://sbolstandard.org/libraries/javascript/

**Comment by cjmyers** [comment]
https://www.npmjs.com/package/sboljs

**Comment by cjmyers** [comment]
Java links are fine.  I cannot find the Javascript version of the CRISPR example right now.  It might be lost.

**Comment by cjmyers** [comment]
Might be good to link to a talk like this one, which is from our IWBDA 2018 tutorial for Java and Javascript:

https://github.com/SynBioDex/Community-Media/blob/master/2018/IWBDA18/SBOLWorkshop2018_java_js.pdf

Basically, cross-listing to latest tutorials on each library page.
