### ISSUE TITLE
SBOL Visual Examples from Goksel

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SbolStandardWebsite#88]
https://pubs.acs.org/na101/home/literatum/publisher/achs/journals/content/asbcd6/2019/asbcd6.2019.8.issue-7/acssynbio.8b00532/20190712/images/large/sb-2018-00532g_0011.jpeg
 from https://pubs.acs.org/doi/10.1021/acssynbio.8b00532 (ACS permission may be necessary, SBOL-OWL paper, 2018)

and Figure 7 from https://dl.acm.org/doi/abs/10.1145/2631921 (Open Access, 2014).

**Comment by Fontanapink** [comment]
For an individual, for non-commercial purposes, permission is granted at no charge for a cumulative total of 4 or fewer figures, tables, or micrographs, or an excerpt of 400 or fewer words for a single article. Appropriate credit should be given. Appropriate credit should read: "Reprinted with permission from {COMPLETE REFERENCE CITATION}. Copyright {YEAR} American Chemical Society." Insert appropriate information in place of the capitalized words. Please save this page for your records and for publication in print provide a copy to your publisher.

For an institution or organization, permission is not granted.

If credit is given to another source for the material you requested from RightsLink, permission must be obtained from that source.

**Comment by cjmyers** [comment]
We can point to the publication even if we do not lift figures from it.

**Comment by Fontanapink** [comment]
Done
