### ISSUE TITLE
Check all links and image references

### ISSUE THREAD

**Issue by PrashantVaidyanathan** [SynBioDex/SbolStandardWebsite#90]
PR #87 introduced a significant restructuring in the repository. Due to this some of the images and links do not show up anymore.

**Comment by jamesscottbrown** [comment]
Some external sites are no longer available:

* http://pobol.org/
* http://biocad.ncl.ac.uk/protein-designer/
* http://www.cbrc.kaust.edu.sa/sbolme

The [community outrach](https://sbolstandard.org/community-outreach/) and [community meetings](https://sbolstandard.org/community-meetings/) pages both have many broken links corresponding to past events. I don't know what these should link to.

**Comment by Fontanapink** [comment]
Fixed the image issues with the last PR. The problem was that in wowchemy 5.0, the "static/img" folder had to be renamed to "static/media". Link: https://wowchemy.com/updates/v5.0.0-beta.0/#apply-breaking-changes

We should check for the other breaking chanches

**Comment by Fontanapink** [comment]
Also, we should check the image source location for the images that @hasanbaig changed on the SBOL Industrial Consortium page, and revert them back to the original reference.

**Comment by jamesscottbrown** [comment]
Also, https://sbolstandard.org/sbol-visual-ontology/ has links that resolve to http://synbiodex.github.io/SBOL-visual/Glyphs/aptamer/aptamer-specification.png and http://synbiodex.github.io/SBOL-visual/Glyphs/aptamer/aptamer-specification.svg which are broken.

**Comment by tcmitchell** [comment]
I ran [linkchecker](https://wummel.github.io/linkchecker/) on `https://sbolstandard.org`. It found 2 errors and took 7 minutes to run.

Summary:
```
Statistics:
Downloaded: 11.4MB.
Content types: 71 image, 658 text, 0 video, 0 audio, 463 application, 8 mail and 1055 other.
URL lengths: min=16, max=378, avg=81.

That's it. 2255 links in 2273 URLs checked. 0 warnings found. 2 errors found.
Stopped checking at 2022-04-06 11:24:13-004 (7 minutes, 6 seconds)
```

Error 1:
```
URL        `http://sbolstandard.org/combine-2017/'
Name       `Slides'
Parent URL https://sbolstandard.org/community-meetings/, line 20, col 3434
Real URL   https://sbolstandard.org/combine-2017/
Check time 3.040 seconds
Size       3KB
Info       Redirected to
           `https://sbolstandard.org/combine-2017/'.
Result     Error: 404 Not Found
```

Error 2:
```
URL        `Introduction to libSBOL and pySBOL'
Name       `Introduction to libSBOL and pySBOL'
Parent URL https://sbolstandard.org/event/2017/iwbda/, line 24, col 4279
Real URL   https://sbolstandard.org/event/2017/iwbda/Introduction%20to%20libSBOL%20and%20pySBOL
Check time 4.360 seconds
Size       3KB
Result     Error: 404 Not Found
```

The first will be easy to fix. For the second we'll have to see if we can find the presentation info.

**Comment by cjmyers** [comment]
You can find it here:

https://github.com/SynBioDex/Community-Media/blob/master/2017/Second%20Annual%20SBOL%20Workshop/SBOL%20Workshop%202017.pptx

**Comment by tcmitchell** [comment]
`linkchecker --check-extern https://sbolstandard.org` reveals the following 10 broken external links:

* http://vows.sbolstandard.org/glyph/SO:0000031/png
* http://biocad.ncl.ac.uk/protein-designer/
* http://www.cbrc.kaust.edu.sa/sbolme
* https://doi.org/10.1073/pnas.1120788109
* https://www.pnas.org/content/109/18/7085
* http://pobol.org
* http://eugenecad.org/
* http://gene-genie.org/
* http://tellurium.analogmachine.org/
* https://www.ebi.ac.uk/about/events/seminars/2017/synthetic-biology-open-language-sbol-and-recent-developments-tools-and-repositories

**Comment by Fontanapink** [comment]
OK so there are a few different types of external links:
1) For tools/software: I would remove external links pointing to software or tooling websites, as these may go down easily and we can't control it. Instead, most of these tools have publications. I would link to those
2) some of the links posted here ARE links to publications. But some of them I can see them properly when clicked (like for example: https://www.pnas.org/content/109/18/7085 ). Does the link-checker tell you exactly where this link is located in the website?

**Comment by Fontanapink** [comment]
Thanks

**Comment by Fontanapink** [comment]
OK this link:

- https://www.pnas.org/content/109/18/7085

- on https://sbolstandard.org/publication/

Still works when I click on it. I haven't tested the other.

**Comment by tcmitchell** [comment]
Perhaps this is just a limitation of the `linkchecker` tool, and perhaps the web site is seeing too many requests from my IP address and is cutting me off temporarily. We can manually check these 10 links and those that work can be taken off the list. It's a small enough set to be manageable at this point.

**Comment by tcmitchell** [comment]
I clicked all the links above, and update the list of broken links, which is now down to 8.

**Comment by cjmyers** [comment]
SBOLMe https://pubs.acs.org/doi/abs/10.1021/acssynbio.6b00278

**Comment by tcmitchell** [comment]
Here is the dispensation of each broken link:

* http://vows.sbolstandard.org/glyph/SO:0000031/png
  * on https://sbolstandard.org/sbol-visual-ontology/
  * _Opened #188 to track this issue_
* http://biocad.ncl.ac.uk/protein-designer/
  * on https://sbolstandard.org/publication/
  * _Won't fix: this is an external link that is part of the publication abstract._
* http://www.cbrc.kaust.edu.sa/sbolme
  * on https://sbolstandard.org/publication/
  * _Won't fix: this is an external link that is part of the publication abstract._
* ~~https://doi.org/10.1073/pnas.1120788109~~
  * on https://sbolstandard.org/publication/
  * _Won't fix: works in a browser_
* ~~https://www.pnas.org/content/109/18/7085~~
  * on https://sbolstandard.org/publication/
  * _Won't fix: works in a browser_
* http://pobol.org
  * on https://sbolstandard.org/publication/
  * _Won't fix: this is an external link that is part of the publication abstract._
  * _Added a link to the publication PDF_
* http://eugenecad.org/
  * on https://sbolstandard.org/applications/eugene/
  * _Updated to https://www.cidarlab.org/eugene_
* http://gene-genie.org/
  * on https://sbolstandard.org/applications/genegenie/
  * _Updated to https://bio.tools/genegenie_
* http://tellurium.analogmachine.org/
  * on https://sbolstandard.org/applications/tellurium/
  * _Updated to https://github.com/sys-bio/tellurium_
* https://www.ebi.ac.uk/about/events/seminars/2017/synthetic-biology-open-language-sbol-and-recent-developments-tools-and-repositories
  * on https://sbolstandard.org/event/2017/embl-ebi/
  * _Link removed in #187 _
